"""add ist_pflegeunfall to bericht

Revision ID: 2fb9853f23eb
Revises: b9d1b68f145f
Create Date: 2026-02-06 20:23:41.647089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2fb9853f23eb'
down_revision = 'b9d1b68f145f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bericht', sa.Column('ist_pflegeunfall', sa.Boolean(), nullable=True))
    op.add_column('bericht', sa.Column('datum_mitteilung_behandelnder_arzt', sa.Date(), nullable=True))
    op.alter_column('bericht', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('bericht', 'kopie_an_kasse',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bericht', 'verdacht_alkohol_drogen',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bericht', 'blutentnahme_durchgefuehrt',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bericht', 'handverletzung',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bericht', 'polytrauma',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bericht', 'zweifel_arbeitsunfall',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bericht', 'verletzung_vav',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bericht', 'verletzung_sav',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bericht', 'weiterbehandlung_durch',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('bericht', 'au_laenger_3_monate',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bericht', 'weitere_aerzte_noetig',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bericht', 'wiedervorstellung_mitgeteilt',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bericht', 'datenschutz_hinweis_gegeben',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bericht', 'ergaenzung_kopfverletzung',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bericht', 'ergaenzung_knieverletzung',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bericht', 'ergaenzung_schulterverletzung',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bericht', 'ergaenzung_verbrennung',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bericht', 'erstellt_am',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bericht', 'aktualisiert_am',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('bericht', 'abgeschlossen_am',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('bericht', 'pdf_generiert_am',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_bericht_benutzer_id'), table_name='bericht')
    op.drop_index(op.f('ix_bericht_patient_id'), table_name='bericht')
    op.drop_index(op.f('ix_bericht_status'), table_name='bericht')
    op.drop_index(op.f('ix_bericht_unfalltag'), table_name='bericht')
    op.alter_column('patient', 'geschlecht',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=1),
               existing_nullable=True)
    op.alter_column('patient', 'familienversichert',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('patient', 'erstellt_am',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('patient', 'aktualisiert_am',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_patient_nachname'), 'patient', ['nachname'], unique=False)
    op.alter_column('unfallbetrieb', 'branche',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('unfallbetrieb', 'erstellt_am',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('unfallbetrieb', 'aktualisiert_am')
    op.alter_column('uv_traeger', 'kuerzel',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('uv_traeger', 'adresse',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('uv_traeger', 'erstellt_am',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uv_traeger', 'erstellt_am',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('uv_traeger', 'adresse',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('uv_traeger', 'kuerzel',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('unfallbetrieb', sa.Column('aktualisiert_am', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('unfallbetrieb', 'erstellt_am',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('unfallbetrieb', 'branche',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_index(op.f('ix_patient_nachname'), table_name='patient')
    op.alter_column('patient', 'aktualisiert_am',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('patient', 'erstellt_am',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('patient', 'familienversichert',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('patient', 'geschlecht',
               existing_type=sa.String(length=1),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.create_index(op.f('ix_bericht_unfalltag'), 'bericht', ['unfalltag'], unique=False)
    op.create_index(op.f('ix_bericht_status'), 'bericht', ['status'], unique=False)
    op.create_index(op.f('ix_bericht_patient_id'), 'bericht', ['patient_id'], unique=False)
    op.create_index(op.f('ix_bericht_benutzer_id'), 'bericht', ['benutzer_id'], unique=False)
    op.alter_column('bericht', 'pdf_generiert_am',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('bericht', 'abgeschlossen_am',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('bericht', 'aktualisiert_am',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('bericht', 'erstellt_am',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bericht', 'ergaenzung_verbrennung',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bericht', 'ergaenzung_schulterverletzung',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bericht', 'ergaenzung_knieverletzung',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bericht', 'ergaenzung_kopfverletzung',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bericht', 'datenschutz_hinweis_gegeben',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bericht', 'wiedervorstellung_mitgeteilt',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bericht', 'weitere_aerzte_noetig',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bericht', 'au_laenger_3_monate',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bericht', 'weiterbehandlung_durch',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('bericht', 'verletzung_sav',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bericht', 'verletzung_vav',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bericht', 'zweifel_arbeitsunfall',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bericht', 'polytrauma',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bericht', 'handverletzung',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bericht', 'blutentnahme_durchgefuehrt',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bericht', 'verdacht_alkohol_drogen',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bericht', 'kopie_an_kasse',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bericht', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('bericht', 'datum_mitteilung_behandelnder_arzt')
    op.drop_column('bericht', 'ist_pflegeunfall')
    # ### end Alembic commands ###