"""Initial tables: benutzer, patient, bericht, etc.

Revision ID: b9d1b68f145f
Revises: 
Create Date: 2026-01-04 17:54:55.928276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d1b68f145f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benutzer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwort_hash', sa.String(length=255), nullable=False),
    sa.Column('vorname', sa.String(length=100), nullable=False),
    sa.Column('nachname', sa.String(length=100), nullable=False),
    sa.Column('titel', sa.String(length=50), nullable=True),
    sa.Column('rolle', sa.String(length=20), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('durchgangsarzt_nr', sa.String(length=50), nullable=True),
    sa.Column('praxis_name', sa.String(length=255), nullable=True),
    sa.Column('praxis_strasse', sa.String(length=255), nullable=True),
    sa.Column('praxis_plz', sa.String(length=10), nullable=True),
    sa.Column('praxis_ort', sa.String(length=100), nullable=True),
    sa.Column('praxis_telefon', sa.String(length=50), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benutzer_email'), 'benutzer', ['email'], unique=True)
    op.create_index(op.f('ix_benutzer_id'), 'benutzer', ['id'], unique=False)
    op.create_table('krankenkasse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kuerzel', sa.String(length=20), nullable=True),
    sa.Column('ik_nummer', sa.String(length=20), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_krankenkasse_id'), 'krankenkasse', ['id'], unique=False)
    op.create_table('unfallbetrieb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('strasse', sa.String(length=255), nullable=True),
    sa.Column('plz', sa.String(length=10), nullable=True),
    sa.Column('ort', sa.String(length=100), nullable=True),
    sa.Column('telefon', sa.String(length=50), nullable=True),
    sa.Column('branche', sa.String(length=100), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unfallbetrieb_id'), 'unfallbetrieb', ['id'], unique=False)
    op.create_table('uv_traeger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kuerzel', sa.String(length=50), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('telefon', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uv_traeger_id'), 'uv_traeger', ['id'], unique=False)
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=100), nullable=False),
    sa.Column('nachname', sa.String(length=100), nullable=False),
    sa.Column('geburtsdatum', sa.Date(), nullable=False),
    sa.Column('geschlecht', sa.String(length=10), nullable=True),
    sa.Column('staatsangehoerigkeit', sa.String(length=100), nullable=True),
    sa.Column('strasse', sa.String(length=255), nullable=True),
    sa.Column('plz', sa.String(length=10), nullable=True),
    sa.Column('ort', sa.String(length=100), nullable=True),
    sa.Column('telefon', sa.String(length=50), nullable=True),
    sa.Column('krankenkasse_id', sa.Integer(), nullable=True),
    sa.Column('familienversichert', sa.Boolean(), nullable=False),
    sa.Column('familienversichert_name', sa.String(length=255), nullable=True),
    sa.Column('pflegekasse', sa.String(length=255), nullable=True),
    sa.Column('beschaeftigt_als', sa.String(length=255), nullable=True),
    sa.Column('beschaeftigt_seit', sa.Date(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['krankenkasse_id'], ['krankenkasse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_id'), 'patient', ['id'], unique=False)
    op.create_table('bericht',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lfd_nr', sa.String(length=50), nullable=False),
    sa.Column('benutzer_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('uv_traeger_id', sa.Integer(), nullable=True),
    sa.Column('unfallbetrieb_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('eingetroffen_datum', sa.Date(), nullable=True),
    sa.Column('eingetroffen_uhrzeit', sa.Time(), nullable=True),
    sa.Column('kopie_an_kasse', sa.Boolean(), nullable=False),
    sa.Column('unfalltag', sa.Date(), nullable=False),
    sa.Column('unfallzeit', sa.Time(), nullable=True),
    sa.Column('unfallort', sa.String(length=255), nullable=True),
    sa.Column('arbeitszeit_beginn', sa.Time(), nullable=True),
    sa.Column('arbeitszeit_ende', sa.Time(), nullable=True),
    sa.Column('unfallhergang', sa.Text(), nullable=True),
    sa.Column('taetigkeit_bei_unfall', sa.Text(), nullable=True),
    sa.Column('verhalten_nach_unfall', sa.Text(), nullable=True),
    sa.Column('art_erstversorgung', sa.Text(), nullable=True),
    sa.Column('erstbehandlung_datum', sa.Date(), nullable=True),
    sa.Column('erstbehandlung_durch', sa.String(length=255), nullable=True),
    sa.Column('verdacht_alkohol_drogen', sa.Boolean(), nullable=False),
    sa.Column('alkohol_drogen_anzeichen', sa.Text(), nullable=True),
    sa.Column('blutentnahme_durchgefuehrt', sa.Boolean(), nullable=False),
    sa.Column('beschwerden_klagen', sa.Text(), nullable=True),
    sa.Column('handverletzung', sa.Boolean(), nullable=False),
    sa.Column('gebrauchshand', sa.String(length=10), nullable=True),
    sa.Column('klinische_befunde', sa.Text(), nullable=True),
    sa.Column('polytrauma', sa.Boolean(), nullable=False),
    sa.Column('iss_score', sa.Integer(), nullable=True),
    sa.Column('bildgebende_diagnostik', sa.Text(), nullable=True),
    sa.Column('erstdiagnose_freitext', sa.Text(), nullable=True),
    sa.Column('erstdiagnose_icd10', sa.String(length=20), nullable=True),
    sa.Column('erstdiagnose_ao', sa.String(length=50), nullable=True),
    sa.Column('art_da_versorgung', sa.Text(), nullable=True),
    sa.Column('vorerkrankungen', sa.Text(), nullable=True),
    sa.Column('zweifel_arbeitsunfall', sa.Boolean(), nullable=False),
    sa.Column('zweifel_begruendung', sa.Text(), nullable=True),
    sa.Column('heilbehandlung_art', sa.String(length=50), nullable=True),
    sa.Column('keine_heilbehandlung_grund', sa.Text(), nullable=True),
    sa.Column('verletzung_vav', sa.Boolean(), nullable=False),
    sa.Column('verletzung_vav_ziffer', sa.String(length=50), nullable=True),
    sa.Column('verletzung_sav', sa.Boolean(), nullable=False),
    sa.Column('verletzung_sav_ziffer', sa.String(length=50), nullable=True),
    sa.Column('weiterbehandlung_durch', sa.String(length=50), nullable=True),
    sa.Column('anderer_arzt_name', sa.String(length=255), nullable=True),
    sa.Column('anderer_arzt_adresse', sa.Text(), nullable=True),
    sa.Column('arbeitsfaehig', sa.Boolean(), nullable=True),
    sa.Column('arbeitsunfaehig_ab', sa.Date(), nullable=True),
    sa.Column('arbeitsfaehig_ab', sa.Date(), nullable=True),
    sa.Column('au_laenger_3_monate', sa.Boolean(), nullable=False),
    sa.Column('weitere_aerzte_noetig', sa.Boolean(), nullable=False),
    sa.Column('weitere_aerzte_namen', sa.Text(), nullable=True),
    sa.Column('wiedervorstellung_datum', sa.Date(), nullable=True),
    sa.Column('wiedervorstellung_mitgeteilt', sa.Boolean(), nullable=False),
    sa.Column('bemerkungen', sa.Text(), nullable=True),
    sa.Column('weitere_ausfuehrungen', sa.Text(), nullable=True),
    sa.Column('datenschutz_hinweis_gegeben', sa.Boolean(), nullable=False),
    sa.Column('mitteilung_behandelnder_arzt', sa.Text(), nullable=True),
    sa.Column('ergaenzung_kopfverletzung', sa.Boolean(), nullable=False),
    sa.Column('ergaenzung_knieverletzung', sa.Boolean(), nullable=False),
    sa.Column('ergaenzung_schulterverletzung', sa.Boolean(), nullable=False),
    sa.Column('ergaenzung_verbrennung', sa.Boolean(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('abgeschlossen_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_generiert_am', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['unfallbetrieb_id'], ['unfallbetrieb.id'], ),
    sa.ForeignKeyConstraint(['uv_traeger_id'], ['uv_traeger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bericht_benutzer_id'), 'bericht', ['benutzer_id'], unique=False)
    op.create_index(op.f('ix_bericht_id'), 'bericht', ['id'], unique=False)
    op.create_index(op.f('ix_bericht_lfd_nr'), 'bericht', ['lfd_nr'], unique=True)
    op.create_index(op.f('ix_bericht_patient_id'), 'bericht', ['patient_id'], unique=False)
    op.create_index(op.f('ix_bericht_status'), 'bericht', ['status'], unique=False)
    op.create_index(op.f('ix_bericht_unfalltag'), 'bericht', ['unfalltag'], unique=False)
    op.create_table('diagnose',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bericht_id', sa.Integer(), nullable=False),
    sa.Column('diagnose_text', sa.Text(), nullable=False),
    sa.Column('icd10_code', sa.String(length=20), nullable=False),
    sa.Column('ao_klassifikation', sa.String(length=50), nullable=True),
    sa.Column('ist_hauptdiagnose', sa.Boolean(), nullable=False),
    sa.Column('reihenfolge', sa.Integer(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bericht_id'], ['bericht.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnose_bericht_id'), 'diagnose', ['bericht_id'], unique=False)
    op.create_index(op.f('ix_diagnose_icd10_code'), 'diagnose', ['icd10_code'], unique=False)
    op.create_index(op.f('ix_diagnose_id'), 'diagnose', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnose_id'), table_name='diagnose')
    op.drop_index(op.f('ix_diagnose_icd10_code'), table_name='diagnose')
    op.drop_index(op.f('ix_diagnose_bericht_id'), table_name='diagnose')
    op.drop_table('diagnose')
    op.drop_index(op.f('ix_bericht_unfalltag'), table_name='bericht')
    op.drop_index(op.f('ix_bericht_status'), table_name='bericht')
    op.drop_index(op.f('ix_bericht_patient_id'), table_name='bericht')
    op.drop_index(op.f('ix_bericht_lfd_nr'), table_name='bericht')
    op.drop_index(op.f('ix_bericht_id'), table_name='bericht')
    op.drop_index(op.f('ix_bericht_benutzer_id'), table_name='bericht')
    op.drop_table('bericht')
    op.drop_index(op.f('ix_patient_id'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_uv_traeger_id'), table_name='uv_traeger')
    op.drop_table('uv_traeger')
    op.drop_index(op.f('ix_unfallbetrieb_id'), table_name='unfallbetrieb')
    op.drop_table('unfallbetrieb')
    op.drop_index(op.f('ix_krankenkasse_id'), table_name='krankenkasse')
    op.drop_table('krankenkasse')
    op.drop_index(op.f('ix_benutzer_id'), table_name='benutzer')
    op.drop_index(op.f('ix_benutzer_email'), table_name='benutzer')
    op.drop_table('benutzer')
    # ### end Alembic commands ###